### PR TITLE
implement paged paginator for GET requests

### PR DESCRIPTION
**Pull request by Azdaroth**
I've played a bit with pagination (originally https://github.com/samselikoff/ember-cli-mirage/issues/710) and here's what I think made most sense so far.

There are parts I'm not 100% happy with, especially modifying original collection (see splice part in PagedPaginator) and just assigning meta as an attribute. Maybe some decorator for a collection would be useful to make it clear that it may contain meta, having meta directly on collection seems a bit odd. And there's no easy yet to inject custom paginator to route handler.

The current pagination and some naming is a bit arbitrary (page[number] and page[size] were suggested in JSONAPI docs: http://jsonapi.org/format/#fetching-pagination, total-records and total-pages seem (arguably) to be used commonly), so not sure if it's fine like that.

Thoughts?

### CODE REVIEW

**Comment by Azdaroth** [comment]
Failing specs on CI, but 100% green on local machine, cool ;). Will fix it with other potential enhancements / updates after review.

**Comment by ashrafhasson** [comment]
:+1:

**Comment by ashrafhasson** [comment]
this is a great addition, thanks!
How would you go about manually paging through the result set and returning a serialised stub if one wanted to override the default shorthand route handler, say in a test?

**Comment by Azdaroth** [comment]
Hmmm, I'm not sure I get it, could you give a code example?

**Comment by ashrafhasson** [comment]
So I have an acceptance-test for a controller of a route that has ember-infinity model loader and wanted to test that setting a filter on the controller will cause the ember-infinity call to the paginated endpoint includes the filter. It works but I'm not entirely sure how to test that. ember-infinity loads more data when it has reached the the bottom of the viewport. I wanted to override the route handler and inspect the queryParams has the filter on the second request to the API. Here's what I have in the controller:

```javascript
    selectedCoonditionsFilter: Ember.observer('selectedUseConditions.@each', function() {
        let filteredVehicles = [];
        let filterConditions = [];

        this.get('selectedUseConditions').forEach((condition) => {
            if (this.get('model')) {
                this.get('model').map((vehicle) => {
                    if (Ember.get(vehicle, 'useCondition') === condition.value) {
                        filteredVehicles.pushObject(vehicle);
                        filterConditions.pushObject(condition.value);
                    }
                });
            }
        });

        this.send('set_query_params', {useConditions: filterConditions});

        if (this.get('selectedUseConditions').length) {
            this.set('filteredVehicles', filteredVehicles);
        } else {
            this.set('filteredVehicles', this.get('model'));
        }
    }),

```

The route receives the filter object and sets the bound param for ember-infinity like so:

```javascript
import Ember from 'ember';
import InfinityRoute from 'ember-infinity/mixins/route';

export default Ember.Route.extend(InfinityRoute, {
    perPageParam: "page[size]",
    pageParam: "page[number]",
    totalPagesParam: "meta.total-pages",

    model() {
	    return this.infinityModel("vehicle", {perPage: 10, startingPage: 1}, {useConditions: "useConditions"});
	  },
    infinityModelUpdated() {
		    // fired up when data is loaded into the model.
		    console.log('updated with more vehicles');
	  },
    infinityModelLoaded() {
		    // fired up when there's no more data to load from the backend.
		    console.log('no more vehicles to load');
    },

    useConditions: null,

    actions: {
        set_query_params(filter) {
            for (var key in filter) {
                if (filter.hasOwnProperty(key)) {
                    this.set(key, filter[key]);
                }
            }
        }
    }
});

```

In the test, I try to assert the queryParam is present:

```javascript
test('setting useCondition causes ember-infinity to include filter as bound query param in request', function(assert) {
    server.createList('vehicle', 10);
    server.createList('vehicle', 1, {useCondition: 'new'});

    let serializerStub = {
        serializeMetaForPagination(totalPages, totalRecords, collection) {
            return {
                'total-pages': totalPages,
                'total-records': totalRecords
            };
        }
    };

    let paginator = new PagedPaginator(serializerStub);

    let requestCount = 0;
    server.get('/vehicles', (schema, request) => {
        let paginatedCollection = paginator.paginate(request, schema.vehicles.all());

        if (requestCount > 0) {
            assert.equal(request.queryParams.useConditions, ['new']);
        }

        requestCount++;
        return paginatedCollection;
    });

    visit('/search');
    click('.option-expander');
    andThen(() => assert.equal(find('.vehicle-post').length, 10, 'finds 10 vehicles prior to filtering'));

    click('.use-condition-checkbox:first');
    triggerEvent('#test-this', 'scroll', [{isInTestEnvironment:test}]).then(() => {
        console.log('here');
    });
    pauseTest();
    andThen(() => {
        assert.equal(find('.vehicle-post').length, 1, 'finds 1 vehicle post-filtering');
    });
});
```

to be honest, I don't know if this is correct or the best way for testing. It's currently failing the last assert and I feel it's because the page need to scroll to the bottom to bring the infinity-loader into the viewport.

Anyways, this might be more suited for a SO question but any comment on this would also be appreciated.
Thanks,

**Comment by Azdaroth** [comment]
Hmm, not sure if I can help much here, I've never used ember-infinity, but based on what it does I wouldn't really make any extra assertions in route handlers and checking query params as it is more of an implementation detail, I'd rather make some integration / acceptance testing, so I'd write one test for the initial content, then somehow force the scrolling and check if some extra elements were added to the page by ember-inifinity, let me know if it makes sense to you.

**Comment by samselikoff** [comment]
This is a great start and thanks for kicking off the work!

Your implementation here will definitely work for some folks but I'd like to think a bit about how we can get general lower-level abstractions in. If we merge this first then work towards lower-level abstractions it could make it hard to undo some of these API decisions. Since Mirage is such a general-purpose tool (aims to support all kinds of backends), it's important to give folks an escape hatch with lower-level primitives.

I love the idea of a paginator, I think this is a great abstraction, and I like the idea of being able to write your own.

I think the fundamental decision we need to make here is, how to attach metadata to a response.

**Comment by samselikoff** [comment]
So I think before we make progress here, we should work on the metadata question.

I've opened https://github.com/samselikoff/ember-cli-mirage/issues/956 to discuss. Feel free to propose an API there, I will also be thinking about this soon.

**Comment by ashrafhasson** [comment]
@Azdaroth thanks for your reply and yes that's what I was attempting as well, if you see in the test's second `andThen`. Agreed, this might be an implementation detail but what if I needed to override the paginator to control what's returned based on the query param (which actually is also the case in my test). As per the current implementation, that's probably possible by overriding the route, I thought.

**Comment by Azdaroth** [comment]
@ashrafhasson Awh, unfortunately there's is no way to inject custom paginator at this moment, in `BaseShorthandRouteHandler` you could pass it as an option, but I haven't figured out it yet how it can be controlled from the route handler level. Check the code where the paginator is instantiated, maybe you will come up with some nice idea how to handle it.

**Comment by Azdaroth** [comment]
@samselikoff I was thinking about some way to customize paginator and later to customize ordering  / filtering processors (I think there were some plans to add those as well), so I added RouteHandlerOptions, would be awesome if you could check the latest commit and provide some feedback about it. If it looks good and the API for that seems nice, I'll add more tests.

**Comment by Azdaroth** [comment]
Hmm, there is some nasty inter-dependency going on in the tests... basically `TestPaginator` is injected in only one of the tests, but it looks like it sticks in other tests as well, even though the nest instance of server is created in each of them :/. No idea so far how it is possible.

**Comment by Azdaroth** [comment]
Wow, that was some nasty mutation going on, gotta watch out how  `_assign` is used :P.

**Comment by samselikoff** [comment]
oof. Good catch, almost seems like we could lint for that (always produce new object instead of augmenting old ones).

**Comment by jfo84** [comment]
What's the status of this? Great work on this repo, but we need first class pagination to use the library. I can help if help is wanted

**Comment by acorncom** [comment]
@jfo84 if you're still up for it, I think we'd all love to see good pagination support :+1:

**Comment by scottkidder** [comment]
I'm interested in adding pagination support here as well. Any other work on this feature?

**Comment by samselikoff** [comment]
@scottkidder I believe this PR is pretty old and was also a bit too aggressive...

What's the use case you're looking for? (What's the server pagination conventions you're using right now?)

**Comment by samselikoff** [comment]
Closing this as stale, but keeping a reference to it in https://github.com/miragejs/miragejs/issues/217 in case we want to reference these APIs.

**Pull request closed without merging**
