### PR TITLE
Bump ember-cli-addon-docs to 0.10.0

### PR DESCRIPTION
**Pull request by cah-briangantzler**

### CODE REVIEW

**Comment by cah-briangantzler** [comment]
Another issue where ember-cli-mirage may support 2.18, but ember-cli-addon-docs does not :(

**Comment by samselikoff** [comment]
Weren't you able to use a check to only run the dummy app on latest ember?

**Comment by cah-briangantzler** [comment]
That check was stopping a problem while running the tests, unfortunately if you look at the error, this is now happening at build time :(

**Comment by samselikoff** [comment]
I think the "real" solution here is to make the docs site a separate app:

https://ember-learn.github.io/ember-cli-addon-docs/docs/standalone-apps

Here's the PR with more info: https://github.com/ember-learn/ember-cli-addon-docs/pull/409

I don't have time to help out but don't think it's a good idea to cut a release with a broken build. Perhaps can ask around to see if someone with time/motivation can help out if you can't do it.

**Comment by cah-briangantzler** [comment]
This can also be solved by dropping the ember-try against 2.18 and updating the docs to say it may support 2.18

Looking at the addon-docs I would think it should be a new repo rather than a mono-repo, which means I need to create a new repo. Do you want to do that so that it can reside under miragejs?  probably call it ember-cli-mirage-docs? This however will also require changing the deploy of the site for github pages, as well as other parts of the deploy.   
 I would also think that converting this could very well lose the previous versions documentation. 

Given all the work that would need to be done to accomplish this, I would think it would be way easier to just drop the ember-try for 2.18.   While it will still work for 2.18, you just wouldnt testing for it.

**Comment by samselikoff** [comment]
Sounds totally reasonable to me! Feel free to drop 2.18 👍

**Comment by samselikoff** [comment]
BTW for a nested app I don't think you need a new repo. The guide says you could e.g. put it in `ember-cli-mirage/docs`. And I think it will still have all the versions.

Honestly the best long-term solution is to get rid of this docs site completely and just point Ember CLI Mirage users to miragejs.com. And add a section for any specific Ember stuff there.

**Comment by cah-briangantzler** [comment]
I have removed the 2.18, waiting for the tests to run now.   I concur with moving the docs to miragejs proper, you already have a section for it pointing back to this addon docs.      Not really a doc write, but you ok with me attempting to write some docs there in an effort to retire the addon docs from here?

**Comment by samselikoff** [comment]
Yes! Absolutely. I would say either an Advanced guide, or just update the Ember Quickstart to have all the ember-specific stuff.

**Comment by cah-briangantzler** [comment]
Is there a way to run miragejs/site locally so that I can see what by edits look like?

**Comment by samselikoff** [comment]
Yep it’s a Gatsby site so clone it then run `yarn develop`

**Comment by cah-briangantzler** [comment]
doing that I get 

```
 yarn develop
yarn run v1.22.5
$ gatsby develop -H 0.0.0.0
success open and validate gatsby-configs - 0.071s
⠋ load plugins
dyld: lazy symbol binding failed: Symbol not found: _g_once_impl
  Referenced from: /Users/brian.gantzler/source-personal/site/node_modules/gatsby-transformer-sharp/node_modules/sharp/build/Release/sharp.node
  Expected in: /Users/brian.gantzler/source-personal/site/node_modules/sharp/build/Release/../../vendor/lib/libvips.42.dylib

dyld: Symbol not found: _g_once_impl
  Referenced from: /Users/brian.gantzler/source-personal/site/node_modules/gatsby-transformer-sharp/node_modules/sharp/build/Release/sharp.node
  Expected in: /Users/brian.gantzler/source-personal/site/node_modules/sharp/build/Release/../../vendor/lib/libvips.42.dylib

error Command failed with signal "SIGKILL".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by samselikoff** [comment]
What version of node?

**Comment by cah-briangantzler** [comment]
was using 12.14.0, but updated to 14.15.1 and got same result 

```
$ node --version
v14.15.1
✔ ~/source-personal/site [master|✔] 
13:19 $ yarn develop
yarn run v1.21.1
$ gatsby develop -H 0.0.0.0
success open and validate gatsby-configs - 0.069s
⠋ load plugins
dyld: lazy symbol binding failed: Symbol not found: _g_once_impl
  Referenced from: /Users/brian.gantzler/source-personal/site/node_modules/gatsby-transformer-sharp/node_modules/sharp/build/Release/sharp.node
  Expected in: /Users/brian.gantzler/source-personal/site/node_modules/sharp/build/Release/../../vendor/lib/libvips.42.dylib

dyld: Symbol not found: _g_once_impl
  Referenced from: /Users/brian.gantzler/source-personal/site/node_modules/gatsby-transformer-sharp/node_modules/sharp/build/Release/sharp.node
  Expected in: /Users/brian.gantzler/source-personal/site/node_modules/sharp/build/Release/../../vendor/lib/libvips.42.dylib

error Command failed with signal "SIGKILL".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by samselikoff** [comment]
Don't know off the top of my head :/ sorry. The site has been building on Netlify though https://app.netlify.com/sites/miragejs/deploys?filter=deploy+previews

**Comment by cah-briangantzler** [comment]
This past. If you could merge it, would like to see if the master branch now works on the website

**Comment by cah-briangantzler** [comment]
Ok, so the master branch on the docs site is working fine, was all addon docs causing the issue

**Comment by samselikoff** [comment]
Awesome!

**Pull request merged**
