### PR TITLE
➖ Remove `lodash` dependency

### PR DESCRIPTION
**Pull request by bartocc**
I might be wrong, but this is the only place in the codebase where we use a lodash function.

lodash is quite big, and even if ember-cli-mirage is only bundled in dev/test builds, this could be refactored with `typeof` and we could completely drop the `lodash` dependency…

### CODE REVIEW

**Review by SergeAstapov — APPROVED** [review]
makes sense

**Comment by cah-briangantzler** [comment]
Prettier gets me every time. Want to add lint-staged to the git commit hook to run it for me 😄

**Comment by bartocc** [comment]
@SergeAstapov I've ran `yarn workspace ember-cli-mirage-docs test:ember` locally and it passes. How can I fix the `CI /Docs` action?

**Comment by SergeAstapov** [comment]
@bartocc the stack trace makes me think the issue caused by some transitive dependency that got drifted:

```
ERROR Summary:

  - broccoliBuilderErrorStack: TypeError: Cannot read property 'program' of undefined
    at DocFactory._inspectExportDefaultDeclaration (/home/runner/work/ember-cli-mirage/ember-cli-mirage/node_modules/esdoc/out/src/Factory/DocFactory.js:136:40)
    at new DocFactory (/home/runner/work/ember-cli-mirage/ember-cli-mirage/node_modules/esdoc/out/src/Factory/DocFactory.js:91:10)
    at Function._traverse (/home/runner/work/ember-cli-mirage/ember-cli-mirage/node_modules/esdoc/out/src/ESDoc.js:232:21)
    at /home/runner/work/ember-cli-mirage/ember-cli-mirage/node_modules/esdoc/out/src/ESDoc.js:114:25
    at Function._walk (/home/runner/work/ember-cli-mirage/ember-cli-mirage/node_modules/esdoc/out/src/ESDoc.js:203:9)
    at Function._walk (/home/runner/work/ember-cli-mirage/ember-cli-mirage/node_modules/esdoc/out/src/ESDoc.js:205:14)
    at Function.generate (/home/runner/work/ember-cli-mirage/ember-cli-mirage/node_modules/esdoc/out/src/ESDoc.js:98:10)
    at generateESDoc (/home/runner/work/ember-cli-mirage/ember-cli-mirage/node_modules/ember-cli-addon-docs-esdoc/lib/preprocessors/generate-esdoc.js:53:11)
    at generateESDocJsonApi (/home/runner/work/ember-cli-mirage/ember-cli-mirage/node_modules/ember-cli-addon-docs-esdoc/lib/preprocessors/generate-esdoc-jsonapi.js:67:14)
    at /home/runner/work/ember-cli-mirage/ember-cli-mirage/node_modules/ember-cli-addon-docs-esdoc/lib/broccoli/generator.js:41:23
```

however <=3.24 scenarios fail with different error
```
Uncaught Error: Could not find module `@glimmer/manager` imported from `(require)`
```

I just saw that exact same error in https://github.com/miguelcobain/ember-css-transitions/runs/6711631246?check_suite_focus=true which makes me think it's again comes from transitive dependency.

I don't have time right to look into root cause, will try to do once I have a chance.

**Comment by bartocc** [comment]
@SergeAstapov any idea how I could help debug the CI?

**Comment by SergeAstapov** [comment]
Thank you @bartocc!

**Pull request merged**
