### PR TITLE
Deprecate miragejs re-exports

### PR DESCRIPTION
**Pull request by SergeAstapov**
@cah-briangantzler this is the dirty but seem to be working solution for re-exports deprecation.

### CODE REVIEW

**Comment by cah-briangantzler** [comment]
This works wonderfully. I googled for some time and was not able to find a way. Might want to write a blog post on this.

**Comment by cah-briangantzler** [comment]
The docs say to import like this 
```
import { Factory } from 'ember-cli-mirage';
```

Does anyone import like this?
```
import Factory from 'ember-cli-mirage/factory';
```

because this file supports that. https://github.com/miragejs/ember-cli-mirage/blob/master/addon/factory.js

There are a few others. May have to deprecate that as well.

**Comment by SergeAstapov** [comment]
@cah-briangantzler lot me take another look, will try to catch all the re-exports as they have to be deprecated

**Comment by cah-briangantzler** [comment]
Ironically ember-cli-mirage still imported the re-exports in its tests instead of mirage proper.  Updated those if you want to take a look. 

https://github.com/miragejs/ember-cli-mirage/pull/2246

**Pull request merged**
